name: Build

on:
  - push
  - workflow_call

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: '16.16.0'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build app
        env:
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          CHAIN_NAME: ${{ secrets.CHAIN_NAME }}
          CHAIN_ENDPOINT: ${{ secrets.CHAIN_ENDPOINT }}
          CHAIN_SYMBOL: ${{ secrets.CHAIN_SYMBOL }}
          CHAIN_DECIMALS: ${{ secrets.CHAIN_DECIMALS }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          SERVICE_ENDPOINT: ${{ secrets.SERVICE_ENDPOINT }}
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: dist
