name: Build

on:
  - push

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: '16.16.0'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build app
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: dist
