name: Deploy

on:
  push:
    branches: [dev]

jobs:
  build-docker:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Werf build
        uses: werf/actions/build@v1.2
        env:
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          CHAIN_NAME: ${{ secrets.CHAIN_NAME }}
          CHAIN_ENDPOINT: ${{ secrets.CHAIN_ENDPOINT }}
          CHAIN_SYMBOL: ${{ secrets.CHAIN_SYMBOL }}
          CHAIN_DECIMALS: ${{ secrets.CHAIN_DECIMALS }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          SERVICE_ENDPOINT: ${{ secrets.SERVICE_ENDPOINT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
